### ISSUE TITLE
Heroku deployment fails when following the quick_start

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/django-simple-deploy#217]
- [x] Document failure
- [x] Run Heroku integration test - does it fail?
- [x] Push the sample blog project manually. Does it fail?
- [x] Clarify any discrepancies about what works and what doesn't.
- [x] Troubleshoot failure
- [x] Implement fix
- [x] Test
- [x] Release

**Comment by ehmatthes** [comment]
Document failure
---

 - Pushed [this project](https://github.com/ehmatthes/dsd_sample_blog_reqtxt).
 - Passed local functionality tests with runserver.
 - Dump:
 ```
% git push heroku main
Enumerating objects: 64, done.
Counting objects: 100% (64/64), done.
Delta compression using up to 4 threads
Compressing objects: 100% (49/49), done.
Writing objects: 100% (64/64), 16.54 KiB | 8.27 MiB/s, done.
Total 64 (delta 16), reused 48 (delta 9), pack-reused 0
remote: Updated 43 paths from 216a05b
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-22 stack
remote: -----> Determining which buildpack to use for this app
remote: -----> Python app detected
remote: -----> No Python version was specified. Using the buildpack default: python-3.11.3
remote:        To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Installing python-3.11.3
remote: -----> Installing pip 23.0.1, setuptools 67.6.1 and wheel 0.40.0
remote: -----> Installing SQLite3
remote: -----> Installing requirements with pip
remote:        Collecting asgiref==3.5.2
remote:          Downloading asgiref-3.5.2-py3-none-any.whl (22 kB)
remote:        Collecting certifi==2022.9.24
remote:          Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
remote:        Collecting charset-normalizer==2.1.1
remote:          Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
remote:        Collecting Django==4.1.2
remote:          Downloading Django-4.1.2-py3-none-any.whl (8.1 MB)
remote:        Collecting django-bootstrap5==22.1
remote:          Downloading django_bootstrap5-22.1-py3-none-any.whl (24 kB)
remote:        Collecting idna==3.4
remote:          Downloading idna-3.4-py3-none-any.whl (61 kB)
remote:        Collecting requests==2.28.1
remote:          Downloading requests-2.28.1-py3-none-any.whl (62 kB)
remote:        Collecting sqlparse==0.4.3
remote:          Downloading sqlparse-0.4.3-py3-none-any.whl (42 kB)
remote:        Collecting urllib3==1.26.12
remote:          Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
remote:        Collecting django-simple-deploy
remote:          Downloading django_simple_deploy-0.5.14-py3-none-any.whl (49 kB)
remote:        Collecting gunicorn
remote:          Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
remote:        Collecting psycopg2<2.9
remote:          Downloading psycopg2-2.8.6.tar.gz (383 kB)
remote:          Preparing metadata (setup.py): started
remote:          Preparing metadata (setup.py): finished with status 'done'
remote:        Collecting dj-database-url
remote:          Downloading dj_database_url-1.3.0-py3-none-any.whl (7.4 kB)
remote:        Collecting whitenoise
remote:          Downloading whitenoise-6.4.0-py3-none-any.whl (19 kB)
remote:        Collecting toml>=0.10.2
remote:          Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
remote:        Collecting typing-extensions>=3.10.0.0
remote:          Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
remote:        Building wheels for collected packages: psycopg2
remote:          Building wheel for psycopg2 (setup.py): started
remote:          Building wheel for psycopg2 (setup.py): finished with status 'done'
remote:          Created wheel for psycopg2: filename=psycopg2-2.8.6-cp311-cp311-linux_x86_64.whl size=147812 sha256=d156e210be89a8c06e54abd2fdbfe4fb363e80824f694df5193bb9d0ff28579c
remote:          Stored in directory: /tmp/pip-ephem-wheel-cache-204cyuj9/wheels/c5/15/c4/c4f53a2bd9538951fcecc425daf455f651e72443c091abcbf3
remote:        Successfully built psycopg2
remote:        Installing collected packages: whitenoise, urllib3, typing-extensions, toml, sqlparse, psycopg2, idna, gunicorn, charset-normalizer, certifi, asgiref, requests, Django, django-simple-deploy, django-bootstrap5, dj-database-url
remote:        Successfully installed Django-4.1.2 asgiref-3.5.2 certifi-2022.9.24 charset-normalizer-2.1.1 dj-database-url-1.3.0 django-bootstrap5-22.1 django-simple-deploy-0.5.14 gunicorn-20.1.0 idna-3.4 psycopg2-2.8.6 requests-2.28.1 sqlparse-0.4.3 toml-0.10.2 typing-extensions-4.5.0 urllib3-1.26.12 whitenoise-6.4.0
remote: -----> $ python manage.py collectstatic --noinput
remote:        Traceback (most recent call last):
remote:          File "/tmp/build_a9a3d91a/manage.py", line 22, in <module>
remote:            main()
remote:          File "/tmp/build_a9a3d91a/manage.py", line 18, in main
remote:            execute_from_command_line(sys.argv)
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
remote:            utility.execute()
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/core/management/__init__.py", line 420, in execute
remote:            django.setup()
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
remote:            apps.populate(settings.INSTALLED_APPS)
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
remote:            app_config.import_models()
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
remote:            self.models_module = import_module(models_module_name)
remote:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
remote:            return _bootstrap._gcd_import(name[level:], package, level)
remote:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
remote:          File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
remote:          File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
remote:          File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
remote:          File "<frozen importlib._bootstrap_external>", line 940, in exec_module
remote:          File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
remote:          File "/tmp/build_a9a3d91a/blogs/models.py", line 2, in <module>
remote:            from django.contrib.auth.models import User
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/contrib/auth/models.py", line 3, in <module>
remote:            from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 49, in <module>
remote:            class AbstractBaseUser(models.Model):
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/base.py", line 141, in __new__
remote:            new_class.add_to_class("_meta", Options(meta, app_label))
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/base.py", line 369, in add_to_class
remote:            value.contribute_to_class(cls, name)
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/options.py", line 231, in contribute_to_class
remote:            self.db_table, connection.ops.max_name_length()
remote:                           ^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/utils/connection.py", line 15, in __getattr__
remote:            return getattr(self._connections[self._alias], item)
remote:                           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/utils/connection.py", line 62, in __getitem__
remote:            conn = self.create_connection(alias)
remote:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/db/utils.py", line 193, in create_connection
remote:            backend = load_backend(db["ENGINE"])
remote:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/db/utils.py", line 113, in load_backen
remote:            return import_module("%s.base" % backend_name)
remote:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
remote:            return _bootstrap._gcd_import(name[level:], package, level)
remote:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 24, in <module>
remote:            import psycopg2 as Database
remote:          File "/app/.heroku/python/lib/python3.11/site-packages/psycopg2/__init__.py", line 51, in <module>
remote:            from psycopg2._psycopg import (                     # noqa
remote:        SystemError: initialization of _psycopg raised unreported exception
remote: 
remote:  !     Error while running '$ python manage.py collectstatic --noinput'.
remote:        See traceback above for details.
remote: 
remote:        You may need to update application code to resolve this error.
remote:        Or, you can disable collectstatic for this application:
remote: 
remote:           $ heroku config:set DISABLE_COLLECTSTATIC=1
remote: 
remote:        https://devcenter.heroku.com/articles/django-assets
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to radiant-hamlet-34710.
remote: 
To https://git.heroku.com/radiant-hamlet-34710.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/radiant-hamlet-34710.git'
```
