### ISSUE TITLE
Run integration tests on Windows

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/django-simple-deploy#238]
Now that unit tests are passing on Windows, make sure integration tests pass on Windows. There's really no way to get to 1.0 without taking this step.

- [x] Verify current integration tests work on macOS:
    - [x] flyio
    - [x] platformsh Note: this is the only platform that needed no updating.
    - [x] heroku (See #242)
- [x] Update integration tests to use Python, and remove all dependence on shell scripts.
    - [x] fly_io
    - [x] platform_sh
    - [x] heroku
- [x] Remove all shell scripts.
- [x] Require pytest to be run with either `unit_tests` or `integration_tests` argument.
- [ ] Convert build_dev_env.sh to Python, and move out of tests dir.
- [ ] Update integration tests to work on Windows.
- [ ] Update test organization.
    - [ ] Move unit tests under a new tests/ dir.
    - [ ] Move integration tests under tests/.
    - [ ] Rename unit_tests -> e2e_tests.
    - [ ] Update docs to reflect all of these changes.
- [ ] Make a new release, as this fixes some bugs ie ALLOWED_HOSTS on Heroku.
- [ ] Update integration tests to pass on VMs with a minimal development environment.
- [ ] Move all non-critical open tasks to other issues, to prioritize pre-1.0 work.

**Comment by ehmatthes** [comment]
- [ ] Consider requiring that only one platform's integration tests be specified on each test run?

**Comment by ehmatthes** [comment]
Working notes
---

- [ ] Update docs with the variety of ways you can call tests: cd unit_tests && pytest, pytest unit_tests, etc. Not root pytest, pytest unit_tests integration_tests.
- [ ] unit_tests -> e2e_tests

**Comment by ehmatthes** [comment]
Update fly_io deployments
---

- [ ] Integration test without automate-all fails. Complains that a fly app has not yet been created, even though one has.
- [ ] Integration test with automat all fails. Complains about not recognizing a region.

**Comment by ehmatthes** [comment]
- [ ] Add a divider between user docs and dev docs in menu?

**Comment by ehmatthes** [comment]
Convert platform_sh test from shell to python
---

- [ ] Probably need to activate the test environment?

**Comment by ehmatthes** [comment]
Refining platform_sh test
---

- [ ] Test pypi deployment.
- [ ] Test poetry project.
- [ ] Test `--automate-all`.

**Comment by ehmatthes** [comment]
pkg_manager
---

- [ ] Handle different package managers better in testing setup scripts.

**Comment by ehmatthes** [comment]
Pipenv fails to generate lock file when calling simple_deploy?
---

From an integration test of local dsd install:

```sh
--- Your project is now configured for deployment on Platform.sh. ---

To deploy your project, you will need to:
- Commit the changes made in the configuration process.
    $ git status
    $ git add .
    $ git commit -am "Configured project for deployment."
- Push your project to Platform.sh' servers:
    $ platform push
- Open your project:
    $ platform url    
- As you develop your project further:
    - Make local changes
    - Commit your local changes
    - Run `platform push`

- You can find a full record of this configuration in the simple_deploy_logs directory.
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
⠼ Locking...
ERROR:pip.subprocessor:[present-rich] Getting requirements to build wheel exited with 1
[ResolutionFailure]:   File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/resolver.py", line 811, in _main
[ResolutionFailure]:       resolve_packages(
[ResolutionFailure]:   File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/resolver.py", line 759, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:       ^^^^^^^^
[ResolutionFailure]:   File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/resolver.py", line 738, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:       ^^^^^^^^^^^^^
[ResolutionFailure]:   File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 1165, in resolve_deps
[ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
[ResolutionFailure]:       ^^^^^^^^^^^^^^^^^^^^^^
[ResolutionFailure]:   File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 964, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 701, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv run pip install <requirement_name> to bypass this mechanism, then run $ pipenv graph to inspect the versions actually installed in the virtualenv.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Getting requirements to build wheel exited with 1

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/__main__.py", line 4, in <module>
    cli()
  File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/cli/command.py", line 369, in lock
    do_lock(
  File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/routines/lock.py", line 79, in do_lock
    venv_resolve_deps(
  File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 1107, in venv_resolve_deps
    c = resolve(cmd, st, project=project)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/gk/y2n2jsfj23g864pdr38rv4ch0000gn/T/pytest-of-eric/pytest-316/blog_project0/b_env/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 1001, in resolve
    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!


Committing changes...
[main 95dd4d9] Configured for deployment.
 5 files changed, 115 insertions(+), 1 deletion(-)
```

**Comment by ehmatthes** [comment]
- [ ] Consider setting a [marker](https://pipenv.pypa.io/en/latest/specifiers/#specifying-package-categories) that will only install psycopg2 to the remote environment.
- [ ] How can we fend off issues with locking not working on end user systems without Postgres?

**Comment by ehmatthes** [comment]
Update Fly.io tests
---

- [ ] Update main test file to run Fly.io deployment.
- [ ] Carry over any improvements from this file to Platform.sh tests.
    - [ ] Better names in helper functions.

**Comment by ehmatthes** [comment]
Update Fly.io deployments
---

- [ ] Testing against PyPI, fails to recognize app name. Fix re in deploy.py?

**Comment by ehmatthes** [comment]
Destroy project in yield section of tmp project fixture
---

This will allow destruction of the project even if there is a breaking failure.

- [ ] Cache the app name, project id, or any other information needed for destruction in the pytest cache.
- [ ] Cache the platform name as well.
- [ ] In yield, pull from cache and call appropriate destroy utility.

**Comment by ehmatthes** [comment]
Update Heroku testing
---

- [ ] Cache app_name.
