### ISSUE TITLE
No such file or directory: 'fly'

### ISSUE THREAD

**Issue by Flimm** [ehmatthes/django-simple-deploy#268]
Before completing the test run:
- What OS are you using?
Ubuntu 23.10
- What project are you deploying? (the sample blog project, or your own project?)
The sample `blog_project`
- What dependency management system are you using?
pipenv
- Which platform are you targeting?
Fly.io

I got this error:

```
$ pipenv run python manage.py simple_deploy --platform fly_io
Configuring project for deployment...
Created /home/flimm/blog_project/simple_deploy_logs.
  Deployment target: fly_io

***** Deployments to Fly.io are experimental at this point ***

- Support for deploying to Fly.io is in an exploratory phase at this point.
- You should only be using this project to deploy to Fly.io at this point if
  you are interested in helping to develop or test the simple_deploy project.
- You should look at the deploy_flyio.py script before running this command,
  so you know what kinds of changes will be made to your project.
- This command will likely fail if you run it more than once.
- This command may not work if you already have a project deployed to Fly.io.
- You should understand the Fly.io console, and be comfortable deleting resources
  that are created during this deployment.
- You may want to cancel this run and deploy to a different platform.

Are you sure you want to do this? (yes|no) 
yes
  Continuing with Fly.io deployment...
  Found .git dir at /home/flimm/blog_project.
Added simple_deploy_logs/ to .gitignore
  Dependency management system: pipenv
  Checking current project requirements...
    Found existing dependencies:
      django
      django-bootstrap5
      requests
      django-simple-deploy
Traceback (most recent call last):
  File "/home/flimm/blog_project/manage.py", line 22, in <module>
    main()
  File "/home/flimm/blog_project/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/flimm/.local/share/virtualenvs/blog_project--_I4JCKn/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/flimm/.local/share/virtualenvs/blog_project--_I4JCKn/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/flimm/.local/share/virtualenvs/blog_project--_I4JCKn/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/flimm/.local/share/virtualenvs/blog_project--_I4JCKn/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flimm/.local/share/virtualenvs/blog_project--_I4JCKn/lib/python3.11/site-packages/simple_deploy/management/commands/simple_deploy.py", line 90, in handle
    self.platform_deployer.validate_platform()
  File "/home/flimm/.local/share/virtualenvs/blog_project--_I4JCKn/lib/python3.11/site-packages/simple_deploy/management/commands/fly_io/deploy.py", line 361, in validate_platform
    self._validate_cli()
  File "/home/flimm/.local/share/virtualenvs/blog_project--_I4JCKn/lib/python3.11/site-packages/simple_deploy/management/commands/fly_io/deploy.py", line 394, in _validate_cli
    output_obj = self.sd.execute_subp_run(cmd)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flimm/.local/share/virtualenvs/blog_project--_I4JCKn/lib/python3.11/site-packages/simple_deploy/management/commands/simple_deploy.py", line 748, in execute_subp_run
    output = subprocess.run(cmd_parts, capture_output=True, check=check)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'fly'
```

I'm confused. I'm guessing that there needs to be a command called `fly`, but the Fly CLI is actually `flyctl`. I've tried installing it, and now it looks like `fly` is a symlink to `flyctl`.

I think it would be good if django-simple-deploy could detect whether `flyctl` is installed, and display a user-friendly error message if it is not.

**Comment by ehmatthes** [comment]
Bugfix
---

- [ ] Run this on an Ubuntu VM without fly cli.
- [ ] Raise error instead of generating traceback.
- [ ] Install Fly CLI.
- [ ] Complete manual run on dev project.
- [ ] Run integration tests.
- [ ] Check this issue with Platform.sh CLI as well.
- [ ] Make release.
- [ ] Announce.

**Comment by Flimm** [comment]
Thanks for looking at this! I'll answer your question:

> Once you installed the CLI, did this error go away? 

Yes. Installing FLY CLI did fix this problem. I'm not sure I'll have time to look at this any further in the near future, but I thought I would contribute a bug report, if nothing else. I know it's not much.

**Comment by ehmatthes** [comment]
> I thought I would contribute a bug report, if nothing else.

This is very much appreciated, thank you!

**Comment by ehmatthes** [comment]
Traceback with no fly app created
---

If you run simple_deploy on Ubuntu without being logged in, it generates a traceback. This message appears in stderr:

```
Error: No access token available. Please login with 'flyctl auth login'
```

- [ ] Log out on macOS and see if this same error appears. (same error)
- [ ] Fix on Ubuntu.
- [ ] Confirm this fixes on macOS as well.

**Comment by ehmatthes** [comment]
Platform.sh run-through on Ubuntu
---

- [ ] Run without CLI installed. (Raises correct error.)
- [ ] Run without CLI authenticated.
- [ ] Run without first creating app.
- [ ] Run with correct usage.
- [ ] Run integration test.
    - [ ] Check if dev server is shut down correctly.
